apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/<project-name>/secrets/hellojsapp-key1/versions/1"
        path: "good1.txt"
      - resourceName: "projects/<project-name>/secrets/hellojsapp-key1/versions/1"
        path: "good2.txt"
